spring:
  datasource:
    url: jdbc:h2:mem:fintrack_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: false

app:
  jwt:
    secret: ZmZpbm5UcmFja0FwaVNlY3JldEtleUZvckp3dEF1dGhTdHJvbmdFbm91Z2gyMDI2
    expiration-in-ms: 86400000

logging:
  level:
    org.hibernate.SQL: off
    org.springframework.security: off
    dev.guilhermesilva.fintrack: debug